#ifndef GPOSITIONSYSTEM_GLOBAL_H
#define GPOSITIONSYSTEM_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GPOSTIONSYTEM_LIBRARY)
#define GPOSTIONSYTEMSHARED_EXPORT Q_DECL_EXPORT
#else
#define GPOSTIONSYTEMSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // GPOSITIONSYSTEM_GLOBAL_H
